ARG NODE_VERSION=20.7.0

FROM node:${NODE_VERSION}-alpine as build

ARG NEXT_PUBLIC_VERCEL_URL
ENV NEXT_PUBLIC_VERCEL_URL=${NEXT_PUBLIC_VERCEL_URL}

ARG NEXT_PUBLIC_REDIRECT_HOST
ENV NEXT_PUBLIC_REDIRECT_HOST=${NEXT_PUBLIC_REDIRECT_HOST}

ARG NEXT_PUBLIC_AUTH_HOST
ENV NEXT_PUBLIC_AUTH_HOST=${NEXT_PUBLIC_AUTH_HOST}

ARG NEXT_PUBLIC_AUTH_CALLBACK
ENV NEXT_PUBLIC_AUTH_CALLBACK=${NEXT_PUBLIC_AUTH_CALLBACK}

ARG NEXT_PUBLIC_AUTH_CLIENT_ID
ENV NEXT_PUBLIC_AUTH_CLIENT_ID=${NEXT_PUBLIC_AUTH_CLIENT_ID}


WORKDIR /app

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

RUN npm ci

COPY . .

RUN npm run build

CMD [ "npm", "run", "start" ]
