import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import { TrpcProvider } from "@/utils/trpc-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TrpcProvider>
          <Header />
          <Providers>{children}</Providers>
          <Toaster />
        </TrpcProvider>
      </body>
    </html>
  );
}
